name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd ~/Desktop/superset-mastery/docker/dev
          docker compose --env-file ../../.env.dev up -d --build
