name: Deploy to Preprod

on:
  push:
    branches:
      - preprod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          cd ~/Desktop/superset-mastery/docker/preprod
          docker compose --env-file ../../.env.preprod up -d --build

      - name: Import dashboards
        run: |
          cd ~/Desktop/superset-mastery
          for zip in dashboards/*.zip; do
            bash scripts/import_dashboard.sh preprod-superset-1 $zip analyst
          done
